# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "prepreferencegenome"
description: Prepare genome files
keywords:
  - index
  - reference
  - fai
  - dict
  - fasta
components:
  - bwamem2/index
  - samtools/faidx
  - picard/createsequencedictionary
  - sentieon/bwaindex
input:
  - fasta:
      type: file
      description: |
        The input fasta file
        Structure: [ fasta ]
      pattern: "*.{fasta/fa}"
output:
  - bwa:
      type: file
      description: BWA genome index files
      pattern: "Directory containing BWA index *.{0132,amb,ann,pac}"
  - bwamem2:
      type: file
      description: BWA2 genome index files
      pattern: "Directory containing BWA index *.{0132,amb,ann,bwt.2bit.64,pac}"
  - fasta_fai:
      type: file
      description: FASTA index file
      pattern: "*.fai"
    - fasta_dict:
      type: file
      description: FASTA dictionary file
      pattern: "*.dict"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@idt-slowney"
maintainers:
  - "@idt-slowney"
